"""LLM synthesis tool that converts pooled research context into final deliverables.

Uses the same BYO-LLM interface as the orchestrator (agent/llm) so the analyst step honors
whichever provider the user has configured, instead of being hardwired to Anthropic.
"""

from __future__ import annotations

from typing import Any

from agent.llm import get_llm_client


async def run(payload: dict[str, Any]) -> dict[str, Any]:
    """Synthesize a final report, playbook, decision-makers, and outreach drafts."""

    print({"tool": "claude_analyst", "payload_keys": sorted(payload.keys())})
    llm = get_llm_client()
    if llm is None:
        return _fallback(payload)

    prompt = f"""
Company: {payload['company']}
Category: {payload['category']}

Web data:
{payload['web_data']}

LinkedIn data:
{payload['linkedin_data']}

Financial data:
{payload['financial_data']}

Competitor data:
{payload['competitor_data']}

Return JSON with keys: report_markdown, campaign_playbook, decision_makers, outreach_drafts.
"""
    try:
        text = await llm.complete_text(
            system=(
                "You are the deep-analysis layer for IntelBox. Use the supplied research context "
                "to produce a market intelligence report. Be specific, commercially useful, and "
                "concise."
            ),
            prompt=prompt,
            max_tokens=4000,
        )
        return {
            "report_markdown": text,
            "campaign_playbook": "## 10. Campaign Playbook\n\nGenerated by the configured LLM.",
            "decision_makers": [],
            "outreach_drafts": [],
        }
    except Exception as exc:  # noqa: BLE001
        print({"tool": "claude_analyst", "fallback": "template", "error": str(exc)})
        return _fallback(payload)


def _fallback(payload: dict[str, Any]) -> dict[str, Any]:
    """Return a deterministic fallback payload when Claude is unavailable."""

    company = payload["company"]
    return {
        "report_markdown": (
            f"# 1. Company Overview\n{company} operates in {payload['category']}.\n\n"
            "# 2. Market Position\nFallback market-position analysis.\n\n"
            "# 3. Competitor Mapping\nFallback competitor analysis.\n\n"
            "# 4. Brand Activity\nFallback brand activity analysis.\n\n"
            "# 5. Experiential & Events Footprint\nFallback experiential analysis.\n\n"
            "# 6. Strategic Watchouts\nFallback strategic watchouts.\n\n"
            "# 7. Decision-Maker Identification\nFallback decision-maker analysis.\n\n"
            "# 8. Contact Intelligence\nFallback contact intelligence.\n\n"
            "# 9. Personalized Outreach\nFallback outreach draft."
        ),
        "campaign_playbook": "## 10. Campaign Playbook\n\n- Concept 1\n- Concept 2\n- Concept 3",
        "decision_makers": [],
        "outreach_drafts": [],
    }
