"""Claude Sonnet synthesis tool that converts pooled context into final deliverables."""

from __future__ import annotations

import os
from typing import Any

try:
    from anthropic import AsyncAnthropic
except ImportError:  # pragma: no cover - dependency may be absent in minimal environments
    AsyncAnthropic = None


async def run(payload: dict[str, Any]) -> dict[str, Any]:
    """Synthesize a final report, playbook, decision-makers, and outreach drafts."""

    print({"tool": "claude_analyst", "payload_keys": sorted(payload.keys())})
    api_key = os.getenv("ANTHROPIC_API_KEY")
    if not api_key or AsyncAnthropic is None:
        return _fallback(payload)

    prompt = f"""
Company: {payload['company']}
Category: {payload['category']}

Web data:
{payload['web_data']}

LinkedIn data:
{payload['linkedin_data']}

Financial data:
{payload['financial_data']}

Competitor data:
{payload['competitor_data']}

Return JSON with keys: report_markdown, campaign_playbook, decision_makers, outreach_drafts.
"""
    try:
        client = AsyncAnthropic(api_key=api_key)
        response = await client.messages.create(
            model="claude-sonnet-4-20250514",
            max_tokens=4000,
            temperature=0.2,
            messages=[{"role": "user", "content": prompt}],
        )
        text_blocks = [block.text for block in response.content if getattr(block, "type", "") == "text"]
        text = "\n".join(text_blocks).strip()
        return {
            "report_markdown": text,
            "campaign_playbook": "## 10. Campaign Playbook\n\nGenerated by Claude.",
            "decision_makers": [],
            "outreach_drafts": [],
        }
    except Exception as exc:  # noqa: BLE001
        print({"tool": "claude_analyst", "fallback": "template", "error": str(exc)})
        return _fallback(payload)


def _fallback(payload: dict[str, Any]) -> dict[str, Any]:
    """Return a deterministic fallback payload when Claude is unavailable."""

    company = payload["company"]
    return {
        "report_markdown": (
            f"# 1. Company Overview\n{company} operates in {payload['category']}.\n\n"
            "# 2. Market Position\nFallback market-position analysis.\n\n"
            "# 3. Competitor Mapping\nFallback competitor analysis.\n\n"
            "# 4. Brand Activity\nFallback brand activity analysis.\n\n"
            "# 5. Experiential & Events Footprint\nFallback experiential analysis.\n\n"
            "# 6. Strategic Watchouts\nFallback strategic watchouts.\n\n"
            "# 7. Decision-Maker Identification\nFallback decision-maker analysis.\n\n"
            "# 8. Contact Intelligence\nFallback contact intelligence.\n\n"
            "# 9. Personalized Outreach\nFallback outreach draft."
        ),
        "campaign_playbook": "## 10. Campaign Playbook\n\n- Concept 1\n- Concept 2\n- Concept 3",
        "decision_makers": [],
        "outreach_drafts": [],
    }
